server:
    port: 9000

# shows more information of log of spring security
logging:
    level:
        org:
            springframework:
                security: TRACE
            flyaway: TRACE
            oauth2: TRACE

spring:
    application:
      name: authorization-server
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/oauth}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USER:laurocorreia}
        password: ${POSTGRES_PASSWORD:Vincere7}
    jpa:
        show-sql: true