server:
    port: ${PORT:9000}

# shows more information of log of spring security
logging:
    level:
        org:
            springframework:
                security: TRACE
            flyaway: TRACE
            oauth2: TRACE

spring:
    application:
      name: authorization-server
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/auth_server}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
    jpa:
        show-sql: true

authorization:
    server:
        settings:
            name: ${AUTHORIZATION_SERVER_URL:http://localhost:9000}