CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   password VARCHAR(255),
   expired BOOLEAN NOT NULL,
   locked BOOLEAN NOT NULL,
   credentials_expired BOOLEAN NOT NULL,
   disabled BOOLEAN NOT NULL,
   CONSTRAINT pk_appuser PRIMARY KEY (id)
);